apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nest-gitops-ingress
spec:
  rules:
  - host: nest-gitops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nest-gitops-svc
            port:
              number: 80
